export const enum DownloadEndpoint {
  DIVORCE_APPLICATION = '/downloads/divorce-application',
  APPLICATION_TO_END_CIVIL_PARTNERSHIP = '/downloads/application-to-end-civil-partnership',
  RESPONDENT_ANSWERS = '/downloads/respondent-answers',
  CERTIFICATE_OF_SERVICE = '/downloads/certificate-of-service',
  CERTIFICATE_OF_DEEMED_AS_SERVICE = '/downloads/certificate-of-deemed-as-service',
  CERTIFICATE_OF_DISPENSE_WITH_SERVICE = '/downloads/certificate-of-dispense-with-service',
  CERTIFICATE_OF_ENTITLEMENT = '/downloads/certificate-of-entitlement',
  CONDITIONAL_ORDER_GRANTED = '/downloads/conditional-order-granted',
  CONDITIONAL_ORDER_ANSWERS = '/downloads/conditional-order-answers',
  CONDITIONAL_ORDER_APPLICATION = '/downloads/conditional-order-application',
  CONDITIONAL_ORDER_REFUSAL = '/downloads/conditional-order-refusal',
  FINAL_ORDER_GRANTED = '/downloads/final-order-granted',
  DEEMED_SERVICE_REFUSED = '/downloads/deemed-service-refused',
  FINAL_ORDER_APPLICATION = '/downloads/final-order-application',
  DISPENSE_WITH_SERVICE_REFUSED = '/downloads/dispense-with-service-refused',
  BAILIFF_SERVICE_REFUSED = '/downloads/bailiff-service-refused',
  BAILIFF_UNSUCCESSFUL_CERTIFICATION_OF_SERVICE = '/downloads/bailiff-unsuccessful-certificate-of-service',
  BAILIFF_SERVICE = '/downloads/bailiff-service',
}
