import { Checkbox } from '../../../../../app/case/case';
import { YesOrNo, YesOrNoOrNotKnown } from '../../../../../app/case/definition';
import { getFilename } from '../../../../../app/case/formatter/uploaded-files';
import { TranslationFn } from '../../../../../app/controller/GetController';
import { FormContent } from '../../../../../app/form/Form';
import * as urls from '../../../../urls';
import {
  form as checkAnswersForm,
  generateContent as checkAnswersGenerateContent,
} from '../../common/check-answers/content';
import type { CommonContent } from '../../../../common/common.content';

const en = ({ userCase, partner }: CommonContent, useHwf, hwfReference, canUpload, uploadedDocsFilenames) => ({
  stepQuestions: {
    useHwf: 'Help paying the application fee',
    hwfReference: 'Help with fees reference number',
    partnerName: `Your ${partner}'s name`,
    partnerInRefuge: `Is your ${partner} in a refuge?`,
    knowPartnersPhone: `Do you know your ${partner}’s phone number?`,
    partnerPhoneNumber: `Your ${partner}'s phone number`,
    knowPartnersDateOfBirth: `Do you know your ${partner}’s date of birth?`,
    partnerDateOfBirth: `Your ${partner}'s date of birth`,
    partnerApproximateAge: `Your ${partner}'s approximate age`,
    partnerHeight: `Your ${partner}'s height`,
    partnerHairColour: `Your ${partner}'s hair colour`,
    partnerEyeColour: `Your ${partner}'s eye colour`,
    partnerEthnicGroup: `Your ${partner}'s ethnic group`,
    partnerDistinguishingFeatures: `Your ${partner}'s distinguishing features`,
    canUploadEvidence: `Are you able to upload a photo of your ${partner}?`,
    uploadedFiles: 'Uploaded photo',
    bestTimeToServePapers: 'When is the best time to serve papers?',
    doesPartnerHaveVehicle: `Does your ${partner} have a vehicle?`,
    partnerVehicleModel: `Your ${partner}'s vehicle model`,
    partnerVehicleColour: `Your ${partner}'s vehicle colour`,
    partnerVehicleRegistration: `Your ${partner}'s vehicle registration`,
    partnerVehicleOtherDetails: `Your ${partner}'s vehicle other details`,
    hasPartnerBeenViolent: `Has your ${partner} been violent?`,
    partnerViolenceDetails: `Details about ${partner}'s violence`,
    hasPartnerMadeThreats: `Has your ${partner} made threats?`,
    partnerThreatsDetails: `Details about ${partner}'s threats`,
    havePoliceBeenInvolved: `Have the police been involved with ${partner}?`,
    policeInvolvedDetails: `Details about police involvement with ${partner}`,
    haveSocialServicesBeenInvolved: `Have social services been involved with ${partner}?`,
    socialServicesInvolvedDetails: `Details about social services involvement with ${partner}`,
    areThereDangerousAnimals: `Are any dogs or other potentially dangerous animals kept at the property?`,
    dangerousAnimalsDetails: `Details about dangerous animals`,
    doesPartnerHaveMentalIssues: `Does your ${partner} have any mental health issues?`,
    partnerMentalIssuesDetails: `Details about ${partner}'s mental health issues`,
    doesPartnerHoldFirearmsLicense: `Does your ${partner} hold a firearms license?`,
    partnerFirearmsLicenseDetails: `Details about ${partner}'s firearms license`,
  },
  stepAnswers: {
    useHwf: `${useHwf}`,
    hwfReference: `${hwfReference}`,
    partnerName: `${userCase.applicant1BailiffPartnersName}`,
    partnerInRefuge: `${userCase.applicant1BailiffPartnerInARefuge}`,
    knowPartnersPhone: `${userCase.applicant1BailiffKnowPartnersPhone}`,
    partnerPhoneNumber: userCase.applicant1BailiffKnowPartnersPhone === YesOrNo.YES && `${userCase.applicant1BailiffPartnersPhone}`,
    knowPartnersDateOfBirth: `${userCase.applicant1BailiffKnowPartnersDateOfBirth}`,
    partnerDateOfBirth: userCase.applicant1BailiffKnowPartnersDateOfBirth === YesOrNo.YES && `${userCase.applicant1BailiffPartnersDateOfBirth}`,
    partnerApproximateAge: userCase.applicant1BailiffKnowPartnersDateOfBirth === YesOrNo.NO && `${userCase.applicant1BailiffPartnersApproximateAge}`,
    partnerHeight: `${userCase.applicant1BailiffPartnersHeight}`,
    partnerHairColour: `${userCase.applicant1BailiffPartnersHairColour}`,
    partnerEyeColour: `${userCase.applicant1BailiffPartnersEyeColour}`,
    partnerEthnicGroup: `${userCase.applicant1BailiffPartnersEthnicGroup}`,
    partnerDistinguishingFeatures: `${userCase.applicant1BailiffPartnersDistinguishingFeatures}`,
    canUploadEvidence: `${canUpload}`,
    uploadedFiles: `${uploadedDocsFilenames}`,
    bestTimeToServePapers: `${userCase.applicant1BailiffBestTimeToServe}`,
    doesPartnerHaveVehicle: `${userCase.applicant1BailiffDoesPartnerHaveVehicle}`,
    partnerVehicleModel: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerVehicleModel}`,
    partnerVehicleColour: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerVehicleColour}`,
    partnerVehicleRegistration: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerVehicleRegistration}`,
    partnerVehicleOtherDetails: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerVehicleOtherDetails}`,
    hasPartnerBeenViolent: `${userCase.applicant1BailiffHasPartnerBeenViolent}`,
    partnerViolenceDetails: userCase.applicant1BailiffHasPartnerBeenViolent === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerViolenceDetails}`,
    hasPartnerMadeThreats: `${userCase.applicant1BailiffHasPartnerMadeThreats}`,
    partnerThreatsDetails: userCase.applicant1BailiffHasPartnerMadeThreats === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerThreatsDetails}`,
    havePoliceBeenInvolved: `${userCase.applicant1BailiffHavePoliceBeenInvolved}`,
    policeInvolvedDetails: userCase.applicant1BailiffHavePoliceBeenInvolved === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPoliceInvolvedDetails}`,
    haveSocialServicesBeenInvolved: `${userCase.applicant1BailiffHaveSocialServicesBeenInvolved}`,
    socialServicesInvolvedDetails: userCase.applicant1BailiffHaveSocialServicesBeenInvolved === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffSocialServicesInvolvedDetails}`,
    areThereDangerousAnimals: `${userCase.applicant1BailiffAreThereDangerousAnimals}`,
    dangerousAnimalsDetails: userCase.applicant1BailiffAreThereDangerousAnimals === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffDangerousAnimalsDetails}`,
    doesPartnerHaveMentalIssues: `${userCase.applicant1BailiffDoesPartnerHaveMentalIssues}`,
    partnerMentalIssuesDetails: userCase.applicant1BailiffDoesPartnerHaveMentalIssues === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerMentalIssuesDetails}`,
    doesPartnerHoldFirearmsLicense: `${userCase.applicant1BailiffDoesPartnerHoldFirearmsLicense}`,
    partnerFirearmsLicenseDetails: userCase.applicant1BailiffDoesPartnerHoldFirearmsLicense === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerFirearmsLicenseDetails}`,
  },
  stepLinks: {
    useHwf: `${urls.HELP_WITH_FEES_BAILIFF}`,
    hwfReference: `${urls.HWF_REFERENCE_NUMBER_INPUT_BAILIFF}`,
    partnerName: `${urls.ENTER_PARTNERS_NAME_BAILIFF}`,
    partnerInRefuge: `${urls.PARTNER_IN_REFUGE_BAILIFF}`,
    knowPartnersPhone: `${urls.PARTNER_PHONE_NUMBER_BAILIFF}`,
    partnerPhoneNumber: userCase.applicant1BailiffKnowPartnersPhone === YesOrNo.YES && `${urls.PARTNER_PHONE_NUMBER_BAILIFF}`,
    knowPartnersDateOfBirth: `${urls.PARTNER_DATE_OF_BIRTH_BAILIFF}`,
    partnerDateOfBirth: userCase.applicant1BailiffKnowPartnersDateOfBirth === YesOrNo.YES && `${urls.PARTNER_DATE_OF_BIRTH_BAILIFF}`,
    partnerApproximateAge: userCase.applicant1BailiffKnowPartnersDateOfBirth === YesOrNo.NO && `${urls.PARTNER_DATE_OF_BIRTH_BAILIFF}`,
    partnerHeight: `${urls.PARTNER_HEIGHT_BAILIFF}`,
    partnerHairColour: `${urls.PARTNER_HAIR_COLOUR_BAILIFF}`,
    partnerEyeColour: `${urls.PARTNER_EYE_COLOUR_BAILIFF}`,
    partnerEthnicGroup: `${urls.PARTNER_ETHNIC_GROUP_BAILIFF}`,
    partnerDistinguishingFeatures: `${urls.PARTNER_DISTINGUISHING_FEATURES_BAILIFF}`,
    canUploadEvidence: `${urls.ABLE_TO_UPLOAD_PARTNER_PHOTO}`,
    uploadedFiles: `${urls.UPLOAD_PARTNER_PHOTO}`,
    bestTimeToServePapers: `${urls.WHEN_IS_BEST_TO_SERVE}`,
    doesPartnerHaveVehicle: `${urls.DOES_PARTNER_HAVE_A_VEHICLE}`,
    partnerVehicleModel: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${urls.PARTNER_VEHICLE_DETAILS}`,
    partnerVehicleColour: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${urls.PARTNER_VEHICLE_DETAILS}`,
    partnerVehicleRegistration: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${urls.PARTNER_VEHICLE_DETAILS}`,
    partnerVehicleOtherDetails: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${urls.PARTNER_VEHICLE_DETAILS}`,
    hasPartnerBeenViolent: `${urls.HAS_PARTNER_BEEN_VIOLENT}`,
    partnerViolenceDetails: userCase.applicant1BailiffHasPartnerBeenViolent === YesOrNoOrNotKnown.YES && `${urls.HAS_PARTNER_BEEN_VIOLENT}`,
    hasPartnerMadeThreats: `${urls.HAS_PARTNER_MADE_THREATS}`,
    partnerThreatsDetails: userCase.applicant1BailiffHasPartnerMadeThreats === YesOrNoOrNotKnown.YES && `${urls.HAS_PARTNER_MADE_THREATS}`,
    havePoliceBeenInvolved: `${urls.HAVE_POLICE_BEEN_INVOLVED}`,
    policeInvolvedDetails: userCase.applicant1BailiffHavePoliceBeenInvolved === YesOrNoOrNotKnown.YES && `${urls.HAVE_POLICE_BEEN_INVOLVED}`,
    haveSocialServicesBeenInvolved: `${urls.HAVE_SOCIAL_SERVICES_BEEN_INVOLVED}`,
    socialServicesInvolvedDetails: userCase.applicant1BailiffHaveSocialServicesBeenInvolved === YesOrNoOrNotKnown.YES && `${urls.HAVE_SOCIAL_SERVICES_BEEN_INVOLVED}`,
    areThereDangerousAnimals: `${urls.ARE_THERE_DANGEROUS_ANIMALS}`,
    dangerousAnimalsDetails: userCase.applicant1BailiffAreThereDangerousAnimals === YesOrNoOrNotKnown.YES && `${urls.ARE_THERE_DANGEROUS_ANIMALS}`,
    doesPartnerHaveMentalIssues: `${urls.PARTNER_MENTAL_HEALTH_BAILIFF}`,
    partnerMentalIssuesDetails: userCase.applicant1BailiffDoesPartnerHaveMentalIssues === YesOrNoOrNotKnown.YES && `${urls.PARTNER_MENTAL_HEALTH_BAILIFF}`,
    doesPartnerHoldFirearmsLicense: `${urls.PARTNER_FIREARMS_LICENSE_BAILIFF}`,
    partnerFirearmsLicenseDetails: userCase.applicant1BailiffDoesPartnerHoldFirearmsLicense === YesOrNoOrNotKnown.YES && `${urls.PARTNER_FIREARMS_LICENSE_BAILIFF}`,
  },
});

const cy: typeof en = (
  { userCase }: CommonContent,
  useHwf,
  hwfReference,
  canUpload,
  uploadedDocsFilenames,
) => ({
  stepQuestions: {
    useHwf: 'Help paying the application fee',
    hwfReference: 'Help with fees reference number',
    partnerName: 'Partner name',
    partnerInRefuge: 'Is your partner in a refuge?',
    knowPartnersPhone: 'Do you know your partner’s phone number?',
    partnerPhoneNumber: 'Partner phone number',
    knowPartnersDateOfBirth: 'Do you know your partner’s date of birth?',
    partnerDateOfBirth: 'Partner date of birth',
    partnerApproximateAge: 'Partner approximate age',
    partnerHeight: 'Partner height',
    partnerHairColour: 'Partner hair colour',
    partnerEyeColour: 'Partner eye colour',
    partnerEthnicGroup: 'Partner ethnic group',
    partnerDistinguishingFeatures: 'Partner distinguishing features',
    canUploadEvidence: 'Are you able to upload a photo?',
    uploadedFiles: 'Uploaded photo',
    bestTimeToServePapers: 'When is the best time to serve papers?',
    doesPartnerHaveVehicle: 'Does your partner have a vehicle?',
    partnerVehicleModel: 'Partner vehicle model',
    partnerVehicleColour: 'Partner vehicle colour',
    partnerVehicleRegistration: 'Partner vehicle registration',
    partnerVehicleOtherDetails: 'Partner vehicle other details',
    hasPartnerBeenViolent: 'Has your partner been violent?',
    partnerViolenceDetails: 'Details about violence',
    hasPartnerMadeThreats: 'Has your partner made threats?',
    partnerThreatsDetails: 'Details about threats',
    havePoliceBeenInvolved: 'Have the police been involved?',
    policeInvolvedDetails: 'Details about police involvement',
    haveSocialServicesBeenInvolved: 'Have social services been involved?',
    socialServicesInvolvedDetails: 'Details about social services involvement',
    areThereDangerousAnimals: 'Are any dogs or other potentially dangerous animals kept at the property?',
    dangerousAnimalsDetails: 'Details about dangerous animals',
    doesPartnerHaveMentalIssues: 'Does your partner have any mental health issues?',
    partnerMentalIssuesDetails: 'Details about mental health issues',
    doesPartnerHoldFirearmsLicense: 'Does your partner hold a firearms license?',
    partnerFirearmsLicenseDetails: 'Details about firearms license',
  },
  stepAnswers: {
    useHwf: `${useHwf}`,
    hwfReference: `${hwfReference}`,
    partnerName: `${userCase.applicant1BailiffPartnersName}`,
    partnerInRefuge: `${userCase.applicant1BailiffPartnerInARefuge}`,
    knowPartnersPhone: `${userCase.applicant1BailiffKnowPartnersPhone}`,
    partnerPhoneNumber: userCase.applicant1BailiffKnowPartnersPhone === YesOrNo.YES && `${userCase.applicant1BailiffPartnersPhone}`,
    knowPartnersDateOfBirth: `${userCase.applicant1BailiffKnowPartnersDateOfBirth}`,
    partnerDateOfBirth: userCase.applicant1BailiffKnowPartnersDateOfBirth === YesOrNo.YES && `${userCase.applicant1BailiffPartnersDateOfBirth}`,
    partnerApproximateAge: userCase.applicant1BailiffKnowPartnersDateOfBirth === YesOrNo.NO && `${userCase.applicant1BailiffPartnersApproximateAge}`,
    partnerHeight: `${userCase.applicant1BailiffPartnersHeight}`,
    partnerHairColour: `${userCase.applicant1BailiffPartnersHairColour}`,
    partnerEyeColour: `${userCase.applicant1BailiffPartnersEyeColour}`,
    partnerEthnicGroup: `${userCase.applicant1BailiffPartnersEthnicGroup}`,
    partnerDistinguishingFeatures: `${userCase.applicant1BailiffPartnersDistinguishingFeatures}`,
    canUploadEvidence: `${canUpload}`,
    uploadedFiles: `${uploadedDocsFilenames}`,
    bestTimeToServePapers: `${userCase.applicant1BailiffBestTimeToServe}`,
    doesPartnerHaveVehicle: `${userCase.applicant1BailiffDoesPartnerHaveVehicle}`,
    partnerVehicleModel: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerVehicleModel}`,
    partnerVehicleColour: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerVehicleColour}`,
    partnerVehicleRegistration: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerVehicleRegistration}`,
    partnerVehicleOtherDetails: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerVehicleOtherDetails}`,
    hasPartnerBeenViolent: `${userCase.applicant1BailiffHasPartnerBeenViolent}`,
    partnerViolenceDetails: userCase.applicant1BailiffHasPartnerBeenViolent === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerViolenceDetails}`,
    hasPartnerMadeThreats: `${userCase.applicant1BailiffHasPartnerMadeThreats}`,
    partnerThreatsDetails: userCase.applicant1BailiffHasPartnerMadeThreats === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerThreatsDetails}`,
    havePoliceBeenInvolved: `${userCase.applicant1BailiffHavePoliceBeenInvolved}`,
    policeInvolvedDetails: userCase.applicant1BailiffHavePoliceBeenInvolved === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPoliceInvolvedDetails}`,
    haveSocialServicesBeenInvolved: `${userCase.applicant1BailiffHaveSocialServicesBeenInvolved}`,
    socialServicesInvolvedDetails: userCase.applicant1BailiffHaveSocialServicesBeenInvolved === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffSocialServicesInvolvedDetails}`,
    areThereDangerousAnimals: `${userCase.applicant1BailiffAreThereDangerousAnimals}`,
    dangerousAnimalsDetails: userCase.applicant1BailiffAreThereDangerousAnimals === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffDangerousAnimalsDetails}`,
    doesPartnerHaveMentalIssues: `${userCase.applicant1BailiffDoesPartnerHaveMentalIssues}`,
    partnerMentalIssuesDetails: userCase.applicant1BailiffDoesPartnerHaveMentalIssues === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerMentalIssuesDetails}`,
    doesPartnerHoldFirearmsLicense: `${userCase.applicant1BailiffDoesPartnerHoldFirearmsLicense}`,
    partnerFirearmsLicenseDetails: userCase.applicant1BailiffDoesPartnerHoldFirearmsLicense === YesOrNoOrNotKnown.YES && `${userCase.applicant1BailiffPartnerFirearmsLicenseDetails}`,
  },
  stepLinks: {
    useHwf: `${urls.HELP_WITH_FEES_BAILIFF}`,
    hwfReference: `${urls.HWF_REFERENCE_NUMBER_INPUT_BAILIFF}`,
    partnerName: `${urls.ENTER_PARTNERS_NAME_BAILIFF}`,
    partnerInRefuge: `${urls.PARTNER_IN_REFUGE_BAILIFF}`,
    knowPartnersPhone: `${urls.PARTNER_PHONE_NUMBER_BAILIFF}`,
    partnerPhoneNumber: userCase.applicant1BailiffKnowPartnersPhone === YesOrNo.YES && `${urls.PARTNER_PHONE_NUMBER_BAILIFF}`,
    knowPartnersDateOfBirth: `${urls.PARTNER_DATE_OF_BIRTH_BAILIFF}`,
    partnerDateOfBirth: userCase.applicant1BailiffKnowPartnersDateOfBirth === YesOrNo.YES && `${urls.PARTNER_DATE_OF_BIRTH_BAILIFF}`,
    partnerApproximateAge: userCase.applicant1BailiffKnowPartnersDateOfBirth === YesOrNo.NO && `${urls.PARTNER_DATE_OF_BIRTH_BAILIFF}`,
    partnerHeight: `${urls.PARTNER_HEIGHT_BAILIFF}`,
    partnerHairColour: `${urls.PARTNER_HAIR_COLOUR_BAILIFF}`,
    partnerEyeColour: `${urls.PARTNER_EYE_COLOUR_BAILIFF}`,
    partnerEthnicGroup: `${urls.PARTNER_ETHNIC_GROUP_BAILIFF}`,
    partnerDistinguishingFeatures: `${urls.PARTNER_DISTINGUISHING_FEATURES_BAILIFF}`,
    canUploadEvidence: `${urls.ABLE_TO_UPLOAD_PARTNER_PHOTO}`,
    uploadedFiles: `${urls.UPLOAD_PARTNER_PHOTO}`,
    bestTimeToServePapers: `${urls.WHEN_IS_BEST_TO_SERVE}`,
    doesPartnerHaveVehicle: `${urls.DOES_PARTNER_HAVE_A_VEHICLE}`,
    partnerVehicleModel: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${urls.PARTNER_VEHICLE_DETAILS}`,
    partnerVehicleColour: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${urls.PARTNER_VEHICLE_DETAILS}`,
    partnerVehicleRegistration: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${urls.PARTNER_VEHICLE_DETAILS}`,
    partnerVehicleOtherDetails: userCase.applicant1BailiffDoesPartnerHaveVehicle === YesOrNoOrNotKnown.YES && `${urls.PARTNER_VEHICLE_DETAILS}`,
    hasPartnerBeenViolent: `${urls.HAS_PARTNER_BEEN_VIOLENT}`,
    partnerViolenceDetails: userCase.applicant1BailiffHasPartnerBeenViolent === YesOrNoOrNotKnown.YES && `${urls.HAS_PARTNER_BEEN_VIOLENT}`,
    hasPartnerMadeThreats: `${urls.HAS_PARTNER_MADE_THREATS}`,
    partnerThreatsDetails: userCase.applicant1BailiffHasPartnerMadeThreats === YesOrNoOrNotKnown.YES && `${urls.HAS_PARTNER_MADE_THREATS}`,
    havePoliceBeenInvolved: `${urls.HAVE_POLICE_BEEN_INVOLVED}`,
    policeInvolvedDetails: userCase.applicant1BailiffHavePoliceBeenInvolved === YesOrNoOrNotKnown.YES && `${urls.HAVE_POLICE_BEEN_INVOLVED}`,
    haveSocialServicesBeenInvolved: `${urls.HAVE_SOCIAL_SERVICES_BEEN_INVOLVED}`,
    socialServicesInvolvedDetails: userCase.applicant1BailiffHaveSocialServicesBeenInvolved === YesOrNoOrNotKnown.YES && `${urls.HAVE_SOCIAL_SERVICES_BEEN_INVOLVED}`,
    areThereDangerousAnimals: `${urls.ARE_THERE_DANGEROUS_ANIMALS}`,
    dangerousAnimalsDetails: userCase.applicant1BailiffAreThereDangerousAnimals === YesOrNoOrNotKnown.YES && `${urls.ARE_THERE_DANGEROUS_ANIMALS}`,
    doesPartnerHaveMentalIssues: `${urls.PARTNER_MENTAL_HEALTH_BAILIFF}`,
    partnerMentalIssuesDetails: userCase.applicant1BailiffDoesPartnerHaveMentalIssues === YesOrNoOrNotKnown.YES && `${urls.PARTNER_MENTAL_HEALTH_BAILIFF}`,
    doesPartnerHoldFirearmsLicense: `${urls.PARTNER_FIREARMS_LICENSE_BAILIFF}`,
    partnerFirearmsLicenseDetails: userCase.applicant1BailiffDoesPartnerHoldFirearmsLicense === YesOrNoOrNotKnown.YES && `${urls.PARTNER_FIREARMS_LICENSE_BAILIFF}`,
  },
});

export const form: FormContent = checkAnswersForm;

const languages = {
  en,
  cy,
};

export const generateContent: TranslationFn = content => {
  const checkAnswersContent = checkAnswersGenerateContent(content);
  const useHwf = content.userCase.applicant1InterimAppsUseHelpWithFees;
  const hwfReference = content.userCase.applicant1InterimAppsHwfRefNumber;
  const canUpload = content.userCase.applicant1InterimAppsCanUploadEvidence;
  const uploadedDocsFilenames =
    canUpload === YesOrNo.YES
      ? content.userCase.applicant1InterimAppsEvidenceDocs?.map(item => getFilename(item.value))
      : undefined;
  const cannotUploadDocs =
    content.userCase.applicant1InterimAppsCannotUploadDocs === Checkbox.Checked ? YesOrNo.YES : YesOrNo.NO;
  const translations = languages[content.language](
    content,
    useHwf,
    hwfReference,
    canUpload,
    uploadedDocsFilenames,
  );
  return {
    ...checkAnswersContent,
    ...translations,
    form,
    useHwf,
    hwfReference,
    canUpload,
    uploadedDocsFilenames,
    cannotUploadDocs,
  };
};
