import { Step } from './applicant1Sequence';
import {
  ENTER_YOUR_ADDRESS_APPLICANT2,
  HAS_RELATIONSHIP_BROKEN_APPLICANT2,
  OTHER_COURT_CASES_APPLICANT2,
  YOUR_NAME_APPLICANT2,
  YOU_NEED_TO_REVIEW_YOUR_APPLICATION,
} from './urls';

export const applicant2Sequence: Step[] = [
  {
    url: YOU_NEED_TO_REVIEW_YOUR_APPLICATION,
    getNextStep: () => HAS_RELATIONSHIP_BROKEN_APPLICANT2,
  },
  {
    url: HAS_RELATIONSHIP_BROKEN_APPLICANT2,
    getNextStep: () => YOUR_NAME_APPLICANT2,
  },
  {
    url: ENTER_YOUR_ADDRESS_APPLICANT2,
    getNextStep: () => OTHER_COURT_CASES_APPLICANT2,
  },
];
