import {
  ACCESSIBILITY_STATEMENT_URL,
  APPLICANT_2,
  CHECK_ANSWERS_URL,
  CONTACT_US,
  COOKIES_URL,
  DETAILS_OTHER_PROCEEDINGS,
  DISPUTING_THE_APPLICATION,
  ENGLISH_OR_WELSH,
  ENTER_YOUR_ACCESS_CODE,
  HABITUALLY_RESIDENT_ENGLAND_WALES,
  HOW_DO_YOU_WANT_TO_RESPOND,
  HOW_THE_COURTS_WILL_CONTACT_YOU,
  JURISDICTION_DOMICILE,
  JURISDICTION_LAST_TWELVE_MONTHS,
  LEGAL_JURISDICTION_OF_THE_COURTS,
  LIVING_ENGLAND_WALES_SIX_MONTHS,
  OTHER_COURT_CASES,
  PRIVACY_POLICY_URL,
  PageLink,
  RESIDUAL_JURISDICTION,
  RESPONDENT,
  REVIEW_THE_APPLICATION,
  TERMS_AND_CONDITIONS_URL,
  WEBCHAT_URL,
  WHERE_YOUR_LIVES_ARE_BASED_URL,
} from './urls';

export const signInNotRequired = (reqPath: string): boolean =>
  [
    ACCESSIBILITY_STATEMENT_URL,
    CONTACT_US,
    COOKIES_URL,
    PRIVACY_POLICY_URL,
    TERMS_AND_CONDITIONS_URL,
    WEBCHAT_URL,
  ].includes(reqPath as PageLink);

export const isLinkingUrl = (reqPath: string): boolean =>
  reqPath.endsWith(APPLICANT_2) || reqPath.endsWith(RESPONDENT) || reqPath.endsWith(ENTER_YOUR_ACCESS_CODE);

export const getAosSteps = (): string[] => {
  const baseUrls = [
    REVIEW_THE_APPLICATION,
    HOW_DO_YOU_WANT_TO_RESPOND,
    DISPUTING_THE_APPLICATION,
    LEGAL_JURISDICTION_OF_THE_COURTS,
    OTHER_COURT_CASES,
    DETAILS_OTHER_PROCEEDINGS,
    HOW_THE_COURTS_WILL_CONTACT_YOU,
    ENGLISH_OR_WELSH,
    CHECK_ANSWERS_URL,
  ];
  return baseUrls.map(url => `${RESPONDENT}${url}`);
};

export const jurisdictionUrls: PageLink[] = [
  WHERE_YOUR_LIVES_ARE_BASED_URL,
  JURISDICTION_DOMICILE,
  JURISDICTION_LAST_TWELVE_MONTHS,
  HABITUALLY_RESIDENT_ENGLAND_WALES,
  LIVING_ENGLAND_WALES_SIX_MONTHS,
  RESIDUAL_JURISDICTION,
];
