services:
  idam:
    authorizationURL: 'https://idam-web-public.aat.platform.hmcts.net/login'
    tokenURL: 'https://idam-api.aat.platform.hmcts.net/o/token'
  cos:
    baseURL: 'http://nfdiv-cos-aat.service.core-compute-aat.internal'
