import { COOKIES_URL } from '../urls';

const en = {
  title: 'Cookies',
  paragraph1: 'A cookie is a small piece of data that&rsquo;s stored on your computer, tablet, or phone when you visit a website. Most websites need cookies to work properly.',
  howAreCookiesUsedParagraph1: 'This service uses them to:',
  howAreCookiesUsedItem1: 'measure how you use the service so it can be updated and improved based on your needs',
  howAreCookiesUsedItem2: 'remember the notifications you&rsquo;ve seen so that you&rsquo;re not shown them again',
  howAreCookiesUsedItem3: 'temporarily store the answers you give',
  howAreCookiesUsedParagraph2: 'Find out more about <a class="govuk-link" href="http://www.aboutcookies.org/">how to manage cookies</a>.',
  howAreCookiesUsedHeading2: 'How cookies are used in the divorce service',
  websiteUsageCookiesHeading3: 'To measure website usage',
  websiteUsageCookiesParagraph1: 'We use Google Analytics software to collect information about how you use this service. We do this to help make sure the service is meeting the needs of its users and to help us make improvements, for example improving site search.',
  websiteUsageCookiesParagraph2: 'Google Analytics stores information about:',
  websiteUsageCookiesItem1: 'the pages you visit',
  websiteUsageCookiesItem2: 'how long you spend on each page',
  websiteUsageCookiesItem3: 'how you got to the service',
  websiteUsageCookiesItem4: 'what you click on while you&rsquo;re visiting the service',
  websiteUsageCookiesParagraph3: 'We allow Google to use or share our analytics data. You can find out more about how Google use this information in their <a class="govuk-link" href="https://www.google.com/policies/privacy/partners/">Privacy Policy</a>.',
  websiteUsageCookiesParagraph4: 'You can <a class="govuk-link" href="https://tools.google.com/dlpage/gaoptout">opt out of Google Analytics</a> if you do not want Google to have access to your information.',
  websiteUsageCookiesParagraph5: 'List of google analytics cookies used.',
  websiteUsageCookiesAriaDescribedby: 'Google Analytics sets the following cookies',
  cookieNameHeader: 'Name',
  cookiePurposeHeader: 'Purpose',
  cookieExpiryHeader: 'Expires',
  googleAnalyticsCookieName1: '_ga',
  googleAnalyticsCookiePurpose1: 'This helps us count how many people visit the service by tracking if you&rsquo;ve visited before',
  googleAnalyticsCookieExpiry1: '2 years',
  googleAnalyticsCookieName2: '_gat',
  googleAnalyticsCookiePurpose2: 'Manages the rate at which page view requests are made',
  googleAnalyticsCookieExpiry2: '10 minutes',
  googleAnalyticsCookieName3: '_gid',
  googleAnalyticsCookiePurpose3: 'Identifies you to the service',
  googleAnalyticsCookieExpiry3: '24 hours',
  introMessageCookiesHeading1: 'To turn our introductory message off',
  introMessageCookiesParagraph1: 'You may see a pop-up welcome message when you first visit the service. We’ll store a cookie so that your computer knows you’ve seen it and knows not to show it again.',
  introMessageCookiesAriaDescribedby: 'List of introductory cookies used.',
  introMessageCookieName1: 'seen_cookie_message',
  introMessageCookiePurpose1: 'Saves a message to let us know that you&rsquo;ve seen our cookie message',
  introMessageCookieExpiry1: '1 month',
  sessionCookiesHeading1: 'To store the answers you&rsquo;ve given during your visit (known as a &lsquo;session&rsquo;)',
  sessionCookiesParagraph1: 'Session cookies are stored on your computer as you travel through a website, and let the website know what you&rsquo;ve seen and done so far. These are temporary cookies and are automatically deleted a short while after you leave the website.',
  sessionCookiesAriaDescribedby: 'List of session cookies used.',
  sessionCookieName1: 'connect.sid',
  sessionCookiePurpose1: 'Carries details of your current session',
  sessionCookieExpiry1: 'When you close your browser',
  identityCookiesHeading1: 'To identify you when you come back to the service',
  identityCookiesParagraph1: 'We use authentication cookies to identify you when you return to the service.',
  identityCookiesAriaDescribedby: 'List of authorisation cookies used.',
  identityCookieName1: '__auth-token',
  identityCookiePurpose1: 'Identifies you to the service',
  identityCookieExpiry1: 'When you close your browser',
  securityCookiesHeading1: 'To make the service more secure',
  securityCookiesParagraph1: 'We set cookies which prevent attackers from modifying the contents of the other cookies we set. This makes the service more secure and protects your personal information.',
  securityCookiesAriaDescribedby: 'List of security cookies used.',
  securityCookieName1: 'TSxxxxxxxx',
  securityCookiePurpose1: 'Protects your session from tampering',
  securityCookieExpiry1: 'When you close your browser',
  securityCookieName2: '__state',
  securityCookiePurpose2: 'Identifies you to the service and secures your authentication',
  securityCookieExpiry2: 'When you close your browser',
  securityCookieName3: '_csrf',
  securityCookiePurpose3: 'Helps protect against forgery',
  securityCookieExpiry3: 'When you close your browser'
};

// TODO replace with translation
const cy: typeof en = {
  title: 'Cookies',
  paragraph1: 'A cookie is a small piece of data that&rsquo;s stored on your computer, tablet, or phone when you visit a website. Most websites need cookies to work properly.',
  howAreCookiesUsedParagraph1: 'This service uses them to:',
  howAreCookiesUsedItem1: 'measure how you use the service so it can be updated and improved based on your needs',
  howAreCookiesUsedItem2: 'remember the notifications you&rsquo;ve seen so that you&rsquo;re not shown them again',
  howAreCookiesUsedItem3: 'temporarily store the answers you give',
  howAreCookiesUsedParagraph2: 'Find out more about <a class="govuk-link" href="http://www.aboutcookies.org/">how to manage cookies.</a>.',
  howAreCookiesUsedHeading2: 'How cookies are used in the divorce service',
  websiteUsageCookiesHeading3: 'To measure website usage',
  websiteUsageCookiesParagraph1: 'We use Google Analytics software to collect information about how you use this service. We do this to help make sure the service is meeting the needs of its users and to help us make improvements, for example improving site search.',
  websiteUsageCookiesParagraph2: 'Google Analytics stores information about:',
  websiteUsageCookiesItem1: 'the pages you visit',
  websiteUsageCookiesItem2: 'how long you spend on each page',
  websiteUsageCookiesItem3: 'how you got to the service',
  websiteUsageCookiesItem4: 'what you click on while you&rsquo;re visiting the service',
  websiteUsageCookiesParagraph3: 'We allow Google to use or share our analytics data. You can find out more about how Google use this information in their <a class="govuk-link" href="https://www.google.com/policies/privacy/partners/">Privacy Policy</a>.',
  websiteUsageCookiesParagraph4: 'You can <a class="govuk-link" href="https://tools.google.com/dlpage/gaoptout">opt out of Google Analytics</a> if you do not want Google to have access to your information.',
  websiteUsageCookiesParagraph5: 'List of google analytics cookies used.',
  websiteUsageCookiesAriaDescribedby: 'Google Analytics sets the following cookies',
  cookieNameHeader: 'Name',
  cookiePurposeHeader: 'Purpose',
  cookieExpiryHeader: 'Expires',
  googleAnalyticsCookieName1: '_ga',
  googleAnalyticsCookiePurpose1: 'This helps us count how many people visit the service by tracking if you&rsquo;ve visited before',
  googleAnalyticsCookieExpiry1: '2 years',
  googleAnalyticsCookieName2: '_gat',
  googleAnalyticsCookiePurpose2: 'Manages the rate at which page view requests are made',
  googleAnalyticsCookieExpiry2: '10 minutes',
  googleAnalyticsCookieName3: '_gid',
  googleAnalyticsCookiePurpose3: 'Identifies you to the service',
  googleAnalyticsCookieExpiry3: '24 hours',
  introMessageCookiesHeading1: 'To turn our introductory message off',
  introMessageCookiesParagraph1: 'You may see a pop-up welcome message when you first visit the service. We’ll store a cookie so that your computer knows you’ve seen it and knows not to show it again.',
  introMessageCookiesAriaDescribedby: 'List of introductory cookies used.',
  introMessageCookieName1: 'seen_cookie_message',
  introMessageCookiePurpose1: 'Saves a message to let us know that you&rsquo;ve seen our cookie message',
  introMessageCookieExpiry1: '1 month',
  sessionCookiesHeading1: 'To store the answers you&rsquo;ve given during your visit (known as a &lsquo;session&rsquo;)',
  sessionCookiesParagraph1: 'Session cookies are stored on your computer as you travel through a website, and let the website know what you&rsquo;ve seen and done so far. These are temporary cookies and are automatically deleted a short while after you leave the website.',
  sessionCookiesAriaDescribedby: 'List of session cookies used.',
  sessionCookieName1: 'connect.sid',
  sessionCookiePurpose1: 'Carries details of your current session',
  sessionCookieExpiry1: 'When you close your browser',
  identityCookiesHeading1: 'To identify you when you come back to the service',
  identityCookiesParagraph1: 'We use authentication cookies to identify you when you return to the service.',
  identityCookiesAriaDescribedby: 'List of authorisation cookies used.',
  identityCookieName1: '__auth-token',
  identityCookiePurpose1: 'Identifies you to the service',
  identityCookieExpiry1: 'When you close your browser',
  securityCookiesHeading1: 'To make the service more secure',
  securityCookiesParagraph1: 'We set cookies which prevent attackers from modifying the contents of the other cookies we set. This makes the service more secure and protects your personal information.',
  securityCookiesAriaDescribedby: 'List of security cookies used.',
  securityCookieName1: 'TSxxxxxxxx',
  securityCookiePurpose1: 'Protects your session from tampering',
  securityCookieExpiry1: 'When you close your browser',
  securityCookieName2: '__state',
  securityCookiePurpose2: 'Identifies you to the service and secures your authentication',
  securityCookieExpiry2: 'When you close your browser',
  securityCookieName3: '_csrf',
  securityCookiePurpose3: 'Helps protect against forgery',
  securityCookieExpiry3: 'When you close your browser'
};

const common = {
  link: COOKIES_URL
};

export const CookiesContent = { en, cy, common };
