tags:
  idam-pr: true

nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  registerAdditionalDns:
    enabled: true
    prefix: dis
    primaryIngressHost: ${SERVICE_FQDN}

idam-pr:
  redirect_uris:
    Divorce:
      - https://${SERVICE_FQDN}/oauth2/callback
      - https://dis-${SERVICE_FQDN}/oauth2/callback
